### ISSUE TITLE
Add possibility for paging

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/dynongo#17]
There is a limit on number of records or amount of data returned. If there is more data, a key is returned that can be used as paging key in the next request. There should be an easy way of doing this.

**Comment by SamVerschueren** [comment]
Will be possible if #37 is implemented.

**Comment by mikedizon** [comment]
Was this ever added?

**Comment by SamVerschueren** [comment]
I believe this is possible with the `raw` method.

```js
Employee
    .findOne({Organisation: 'Amazon'})
    .where({Salary: {$gt: 3000}})
    .select('FirstName Name')
    .raw()
    .exec()
    .then(result => {
        console.log(result);
    });
```

This will return the raw result from DynamoDB which should give you enough information to make a new call for the next page. If this doesn't work out, let me know and I'll double check.

**Comment by mikedizon** [comment]
I get a dictionary with Items, Count, and ScannedCount, but nothing that allows me to set the number of results returned in a set, or a token for the next set of results.

**Comment by mikedizon** [comment]
Actually, I just saw that I had to add .limit(x) before executing. What I don't see is how to utilize LastEvaluatedKey.

**Comment by SamVerschueren** [comment]
Well, the thing that this issues covers is that DynamoDB only returns 100 items if I'm not mistaken. Even though you might have 200 items for instance. If that's the case, then the raw result will indeed return a dictionary that also have a key that can be used to retrieve the next page.

If you want paging for let's say 20 items, you will have to implement it yourself. It could work like this

1. Limit the result to let's say 21 items on your server
2. Pop of the last item in the list and return the primary key and sorting key as `next` item of your result

Your result will then look like this

```js
{
    items: [...],
    paging: {
        next: {
            organisation: 'Amazon',
            employeeId: 21
        }
    }
}
```

Then send the request for your next page with the `id` and `sortKey` of the `paging.next` object (with a querystring or something). And then you can easily do this

```js
Employee
    .find({Organisation: 'Amazon', EmployeeId: {$gte: 21}})
    .exec();
```

And do all logic again.

**Comment by mikedizon** [comment]
How can that be done if the ID's are non-numeric?

**Comment by SamVerschueren** [comment]
The same way. The comparison operators also work on strings. You can test these things out in your DynamoDB console by executing a query and play around with the primary key and sorting key values to see what you can achieve. Dynongo could help you achieve that, but under the covers it just uses the DynamoDB API. So I don't think there is more that I can do to improve this. If you have any ideas though, feel free to suggest them.
