### ISSUE TITLE
insert with subdocument

### ISSUE THREAD

**Issue by mikedizon** [SamVerschueren/dynongo#42]
Getting unknown operator _varName_ when trying to insert a JSON object with nested documents. Is this not supported?

**Comment by SamVerschueren** [comment]
It is supported. Can you show me a small example that's not working for you?

**Comment by mikedizon** [comment]
`product.insert(
  {
       "id": "6dc798c4d9dcd4cb72b3e590b2287a9b98f12c9b",
       "foo": {"id": "123", "email": "abc@example.com"},
       "shippingAddress":{
         "shipping_address_city": "New York City",
         "shipping_address_country": "United States",
         "shipping_address_country_code": "US",
         "shipping_address_line1": "123 Fake St",
         "shipping_address_state": "NY",
         "shipping_address_zip": "10005",
         "shipping_name": "MICHAEL DIZON"
       }
     }
).exec().then(
  reference => {
     console.log('reference', reference)
 })`

**Comment by mikedizon** [comment]
http://dpaste.com/074RGWY

**Comment by SamVerschueren** [comment]
It might be not clear from the docs, I should really work on that (PRs are always welcome :)), but [insert](https://github.com/SamVerschueren/dynongo#insert) expects 2 arguments. The first object being the primary index + optional global secondary index. The second argument being the rest of the document. So in your case, I think it should be something like this:

Could you try this one?

``` js
product.insert(
    {
        id: '6dc798c4d9dcd4cb72b3e590b2287a9b98f12c9b'
    },
    {
        foo: {
            id: '123', 
            email: 'abc@example.com'
        },
        shippingAddress: {
            shipping_address_city: 'New York City',
            shipping_address_country: 'United States',
            shipping_address_country_code: 'US',
            shipping_address_line1: '123 Fake St',
            shipping_address_state: 'NY',
            shipping_address_zip: '10005',
            shipping_name: 'Name'
        }
    }
).exec().then(
  reference => {
     console.log('reference', reference)
})
```

**Comment by mikedizon** [comment]
Getting SyntaxError: missing ) after argument list

**Comment by SamVerschueren** [comment]
Can you take a screenshot of the error or copy paste it here in GitHub? This could provide me with useful information.

**Comment by mikedizon** [comment]
Here you go

http://dpaste.com/1QFMSSR

**Comment by SamVerschueren** [comment]
This is not a dynongo issue. Aren't you using a file to write that code?

Save as `index.js`

``` js
'use strict';
const db = require('dynongo');

db.connect({
    accessKeyId: 'accessKeyId',
    secretAccessKey: 'secretAccessKey',
    region: 'us-west-1'
});

// In case `Product` is your table name
const product = db.table('Product');

// Add your product.insert code here
```

Make sure to `npm install dynongo` first and then run

> $ node index.js

**Comment by mikedizon** [comment]
Just ran that, nothing printed. I'm currently debugging in the terminal if that makes any difference.

**Comment by mikedizon** [comment]
oh wow, that worked. can I not use this in a terminal session?

**Comment by SamVerschueren** [comment]
I don't think you can require packages right? If it is possible, then just make sure you did everything like I showed. If not, then no :).
