### ISSUE TITLE
Add the possibility for a batch get

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/dynongo#5]
We should have a method that can retrieve a list of items via a `batchGetItem`.

**Comment by SamVerschueren** [comment]
Can't think of a use case where I want this.

**Comment by Gerst20051** [comment]
I have a list of IDs I need to retrieve rather than looping through them and doing multiple operations this should be able to be done in a single operation.

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html

Any updated thoughts on this? @SamVerschueren
