### ISSUE TITLE
Objects can't be empty

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/dynongo#55]
When you provide a query which results in empty `AttributeValues` for instance, this will fail when executed against DynamoDB.

**Comment by wankunpp** [comment]
Remove `ExpressionAttributeValues` if it is an empty object will make it work for me.

**Comment by SamVerschueren** [comment]
I made this issue a long time ago and can't really recall when this exactly happens. Do you have a small query example that I can use which fails so I can test your solution?

**Comment by SamVerschueren** [comment]
Ok, I found out that when using `.where({firstName: {$exists: true}})` causes this error.
