### ISSUE TITLE
Add Support For Transactions

### ISSUE THREAD

**Issue by Gerst20051** [SamVerschueren/dynongo#62]
@SamVerschueren are you planning on maintaining this project in the future?

What are your thoughts on adding support for transactions?

The new operations are `TransactWriteItems` and `TransactGetItems`.

https://aws.amazon.com/blogs/aws/new-amazon-dynamodb-transactions/
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transactions.html

**Comment by SamVerschueren** [comment]
Yes I do and yes I plan on adding support for it.

**Comment by Gerst20051** [comment]
Hey @SamVerschueren do you have any update on this? Maybe you can share your thoughts on how you plan to implement this and what your timeline looks like? Thanks!

**Comment by SamVerschueren** [comment]
I'm working on this as we speak. You can follow the progress in #64. Hoping to do a release tomorrow with the support.

**Comment by Gerst20051** [comment]
Thanks a lot @SamVerschueren
