### ISSUE TITLE
Add Support For ConsistentRead

### ISSUE THREAD

**Issue by Gerst20051** [SamVerschueren/dynongo#63]
Do you plan to add support for the `ConsistentRead: true` param?

It's similar to how the following params are passed in the request `TableName, KeyConditionExpression, ExpressionAttributeValues, IndexName`.

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html

**Comment by Gerst20051** [comment]
This should be a quick one @SamVerschueren any update on this one?

**Comment by SamVerschueren** [comment]
I'm open for a PR to add a `.consistent()` method on read and write operations. Should be super easy to do.

**Comment by SamVerschueren** [comment]
I was wrong, should only be added to the `find()` and `findOne()` APIs.
