### ISSUE TITLE
Expose all TypeScript typings

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/dynongo#71]
Currently, the types for `Scan` and `Query` are not exposed in the main file. This means that you have to import them via `import {Scan} from 'dynongo/src/lib/methods';` (or something). What we want is to be able to do `import {Scan} from 'dynongo';`.

**Comment by MrCube42** [comment]
@SamVerschueren Just `Query` and `Scan` or everything under /methods? Do you also want to shortcut inside of the lib which means I would also add index files in subfolders? Otherwise you just have to reexport in dynogo/index.ts. I can do this.

**Comment by bartcallant** [comment]
PR: https://github.com/SamVerschueren/dynongo/pull/72

Found one naming collision.

**Comment by bartcallant** [comment]
@devinmotion sorry, did not see your comment. I had already done something like this some time ago, just needed to finish it..

**Comment by MrCube42** [comment]
@bartcallant No problem. First come, first serve ;)
Nicely done 👍 . I just left a comment to your PR. You may consider it.
