### ISSUE TITLE
How to query for array elements

### ISSUE THREAD

**Issue by gabmontes** [SamVerschueren/dynongo#74]
Let's say I have the following document:

```json
{
  "id": 123,
  "key": ["value1", "value2"]
}
```

Using [Mongo `$eq` query syntax](https://docs.mongodb.com/manual/reference/operator/query/eq/#array-element-equals-a-value), this query should match the document as `"value1"` is present in the `key` array:

```js
table.find().where({ key: 'value1' }
```

But I'm getting no results. What is the proper way to do so, if supported, using this library?

**Comment by dmombour** [comment]
try this... .where({ key: { $contains: "value1" } })

**Comment by gabmontes** [comment]
@dmombour `$contains` did the job! Thanks!
